.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, praktikumsplaner-frontend/frontend/package-lock.json
Added OSS templates for feature requests and bug reports
=> OSS Templates

.github/ISSUE_TEMPLATE/default_issue.md, .github/ISSUE_TEMPLATE/user_story.md
**Description**
This PR added an issue template including the Definition of Ready to improve the consistency and structure of user stories in our project.
**Reference**
Issues #43
=> 🔀 Issue Template including Definition of Ready

praktikumsplaner-backend/src/main/resources/application-local.yml, stack/README.md, stack/docker-compose.yml, stack/local-docker-backend.env, stack/local-docker-frontend.env
**Description**
docker compose file to start the infrastructure on local docker. Right now its only backend and frontend. Readme with description is included. Was inspired by digiWf
=> docker compose file for local run

doc/src/documentation/guides/technical-setup/README.md, praktikumsplaner-backend/pom.xml, praktikumsplaner-backend/src/main/resources/application-db-postgres.yml, praktikumsplaner-backend/src/main/resources/application.yml
- Postgresql-Fähigkeit hinzugefügt
- das Standardverhalten habe ich noch nicht auf Postgre umgestellt da ich noch nicht sicher bin dass bei jedem Docker läuft. Außerdem sollte zuvor Flyway drauf.
- es gibt ein zusätzliches Profil für die lokale Entwicklung
- Die Anpassung im Dockerstack kommt über einen gesonderten PR
---
=> Add postgres dependency

.github/ISSUE_TEMPLATE/pull_request_template.md, .github/ISSUE_TEMPLATE/user_story.md
**Description**
**Reference**
Issues #44
=> 📝 added Definition of Done to standard issue template and added a PR template with the DoD

.github/workflows/release-services.yml
- added a triggerable workflow to realease an image with a specific tag
---
=> Create release workflow

.github/pull_request_template.md
=> 🔧 added mentions to PR request and removed top half

README.md
Updated ReadMe sections: Set up, Documentation
=> 🔀 Readme update

doc/src/features/ExcelImport.md, praktikumsplaner-frontend/frontend/src/App.vue, praktikumsplaner-frontend/frontend/src/EventBus.ts, praktikumsplaner-frontend/frontend/src/api/MeldezeitraumService.ts, praktikumsplaner-frontend/frontend/src/components/ExcelImportNWK.vue, praktikumsplaner-frontend/frontend/src/plugins/vuetify.ts, praktikumsplaner-frontend/frontend/src/router.ts
Implemented this design: https://www.figma.com/file/ZqUDvgys2aicPSzNPUf76a/NWK-anlegen-Excel-Import%2313?type=design&node-id=0%3A1&mode=design&t=kcs9AM8bxcJzkqeP-1
**Reference:**
Issue: #13 
---
=> 🔀💄 Implemented new design for Excel Import

.github/ISSUE_TEMPLATE/uiuxrework.md
Added Template to report a ui/ux rework problem
=> 🔀📝 Create uiuxrework.md

doc/src/.vuepress/config.js, doc/src/documentation/guides/local-development/README.md, praktikumsplaner-frontend/frontend/.env.developmentSecurity, praktikumsplaner-frontend/frontend/package.json, praktikumsplaner-frontend/frontend/src/api/FetchUtils.ts
This PR enables developers to use the vite dev server  with active security, so that security related features can be tested easily with hot reloading.
=> 🔀🧑‍💻 local development security active

.github/ISSUE_TEMPLATE/uiuxrework.md, doc/src/.vuepress/components/adr/status.vue, doc/src/.vuepress/config.js, doc/src/.vuepress/theme/layouts/GlobalLayout.vue, doc/src/documentation/README.md, doc/src/documentation/TOOLS.md, doc/src/documentation/architecture/adr/adr000-template.md, doc/src/documentation/architecture/adr/adr001-use-final.md, doc/src/documentation/architecture/adr/adr002-no-hibernate-column-annotation.md, doc/src/documentation/architecture/adr/adr003-test-as-prefix-for-tests.md, doc/src/documentation/architecture/adr/adr004-testing-of-mapping.md, doc/src/documentation/architecture/adr/adr005-dtos-as-records.md, doc/src/documentation/architecture/adr/adr006-kiss-frontend-components.md, doc/src/documentation/architecture/adr/adr007-send-errormessage.md, doc/src/documentation/architecture/adr/adr008-security-roles.md, doc/src/documentation/architecture/adrs.md, doc/src/documentation/architecture/configuration.md, doc/src/documentation/architecture/overview.md, doc/src/documentation/architecture/security/README.md, doc/src/documentation/guides/database-migration/README.md, doc/src/documentation/guides/technical-setup/README.md, doc/src/features/ExcelImport.md, doc/src/features/MeldungOertlAusbilder.md, doc/src/features/meldezeitraum.md, doc/src/glossary.md, doc/src/imprint/README.md, doc/src/index.md
Spell- and grammar checked everything. Updated non translated parts to English.
=> 🔀📝Updated Docs

praktikumsplaner-frontend/frontend/src/composables/rules.ts, praktikumsplaner-frontend/frontend/src/views/MeldungPraktikumsstelle/MeldungAusbildung.vue, praktikumsplaner-frontend/frontend/src/views/MeldungPraktikumsstelle/MeldungStudium.vue, praktikumsplaner-frontend/frontend/tests/unit/rules.spec.ts
Added null and undefined checks to all rules, added tests for all rules, slight reformatting.
**Reference:**
Closes #110 
=> 🔀✅🎨 Rules Composable rework and added tests

praktikumsplaner-frontend/frontend/src/views/MeldungPraktikumsstelle/MeldungAusbildung.vue, praktikumsplaner-frontend/frontend/src/views/MeldungPraktikumsstelle/MeldungStudium.vue
Removed fixed height limit of textareas
**Reference:**
closes #92 
=> 🔀🐛 Fixed textareas stay same height bug

praktikumsplaner-backend/src/main/java/de/muenchen/oss/praktikumsplaner/repository/NWKRepository.java, praktikumsplaner-backend/src/main/java/de/muenchen/oss/praktikumsplaner/service/NWKService.java, praktikumsplaner-backend/src/main/resources/db/migration/V8.1__fix_active_colum_name.sql
Renamed repository methods to active
=> 🔀🗃️🚑️ Renamed repository merthods

praktikumsplaner-backend/checkstyle.xml, praktikumsplaner-backend/src/main/java/de/muenchen/oss/praktikumsplaner/domain/AusbildungsPraktikumsstelle.java, praktikumsplaner-backend/src/main/java/de/muenchen/oss/praktikumsplaner/domain/StudiumsPraktikumsstelle.java
Rule that prevents unused imports has been added. The rule has also been applied directly and existing violations have been fixed.
**Reference:**
Issue: #119 
---
=> 🔀🔧 Checkstyle unused imports

praktikumsplaner-backend/src/main/java/de/muenchen/oss/praktikumsplaner/domain/BasePraktikumsstelle.java, praktikumsplaner-backend/src/main/java/de/muenchen/oss/praktikumsplaner/exception/GlobalExceptionHandler.java, praktikumsplaner-frontend/frontend/src/composables/rules.ts, praktikumsplaner-frontend/frontend/src/views/MeldungPraktikumsstelle/MeldungAusbildung.vue, praktikumsplaner-frontend/frontend/src/views/MeldungPraktikumsstelle/MeldungStudium.vue
added PostgreSQL Exception to the GlobalExceptionHandler, that returns a HTTP 400 Code
**Reference:**
Issue: #91 
=> 🔀🦺 added frontend validation to match backend and database

praktikumsplaner-frontend/frontend/src/composables/rules.ts, praktikumsplaner-frontend/frontend/tests/unit/rules.spec.ts
Boolean rule has been adapted so that a "Nein" or false is accepted and is possible to select.
**Reference:**
Issue: #118 
=> 🚑️🔀 Bugfix/Boolean Meldung 

doc/src/features/MeldungOertlAusbilder.md, praktikumsplaner-backend/src/main/java/de/muenchen/oss/praktikumsplaner/rest/MeldezeitraumController.java, praktikumsplaner-frontend/frontend/src/api/MeldezeitraumService.ts, praktikumsplaner-frontend/frontend/src/components/Meldezeitraeume/CreateMeldezeitraum.vue, praktikumsplaner-frontend/frontend/src/views/MeldungPraktikumsstelle/MeldungAusbildung.vue, praktikumsplaner-frontend/frontend/src/views/MeldungPraktikumsstelle/MeldungStart.vue, praktikumsplaner-frontend/frontend/src/views/MeldungPraktikumsstelle/MeldungStudium.vue
If there is no active Meldezeitraum then the frontend will display a message that you cant submit Prakitkumsstellen.
**Reference:**
Issue: #94 
---
=> 🔀✨ no meldung without meldezeitraum

praktikumsplaner-frontend/frontend/src/components/Meldezeitraeume/CreateMeldezeitraum.vue, praktikumsplaner-frontend/frontend/src/components/Meldezeitraeume/ZeitraumPicker.vue, praktikumsplaner-frontend/frontend/src/components/common/PageTitle.vue, praktikumsplaner-frontend/frontend/src/views/MeldezeitraeumeView.vue, praktikumsplaner-frontend/frontend/tests/unit/zeitraumpicker.spec.ts
Implements the reworked design for #31
**Reference:**
Issue: #104
---
=> 🔀💄 meldezeitraum design rework

doc/src/features/meldezeitraum.md, praktikumsplaner-backend/src/main/java/de/muenchen/oss/praktikumsplaner/repository/MeldezeitraumRepository.java, praktikumsplaner-backend/src/main/java/de/muenchen/oss/praktikumsplaner/rest/MeldezeitraumController.java, praktikumsplaner-backend/src/main/java/de/muenchen/oss/praktikumsplaner/service/MeldezeitraumService.java, praktikumsplaner-backend/src/test/java/de/muenchen/oss/praktikumsplaner/service/MeldezeitraumServiceTest.java, praktikumsplaner-frontend/frontend/src/api/MeldezeitraumService.ts, praktikumsplaner-frontend/frontend/src/components/Meldezeitraeume/CreateMeldezeitraum.vue, praktikumsplaner-frontend/frontend/src/components/Meldezeitraeume/MeldezeitraumList.vue, praktikumsplaner-frontend/frontend/src/composables/formatter.ts, praktikumsplaner-frontend/frontend/src/types/Meldezeitraum.ts, praktikumsplaner-frontend/frontend/src/views/MeldezeitraeumeView.vue
Implements the functionality for the Ausbildungsleitung to see all Meldezeiträume.
**Reference:**
Issue: #133 
---
=> 🔀✨ meldezeitraum uebersicht

praktikumsplaner-frontend/frontend/src/views/MeldungPraktikumsstelle/MeldungStart.vue
Design built in.
**Reference:**
Issue: #99
=> 💄🔀 Design Rework: Kein Meldezeitraum verfügbar

praktikumsplaner-backend/src/main/java/de/muenchen/oss/praktikumsplaner/configuration/MailConfiguration.java, praktikumsplaner-backend/src/main/java/de/muenchen/oss/praktikumsplaner/service/MailService.java, praktikumsplaner-backend/src/main/resources/application.yml, praktikumsplaner-backend/src/test/java/de/muenchen/oss/praktikumsplaner/service/MailServiceTest.java
Added correct mail sender and added mail configration.
=> 🚑️ fixed mailservice configuration

praktikumsplaner-frontend/frontend/src/views/Praktikumsplaetze/MeldungAusbildung.vue, praktikumsplaner-frontend/frontend/src/views/Praktikumsplaetze/MeldungStudium.vue
A short description about the request.
**Reference:**
Issue: #XXX
---
=> 🐛 fixed role problem

doc/src/features/Praktikumsplaetze.md, praktikumsplaner-frontend/frontend/src/views/Praktikumsplaetze/MeldungAusbildung.vue, praktikumsplaner-frontend/frontend/src/views/Praktikumsplaetze/MeldungStudium.vue
added the sorting of Meldezeiträume in Praktikumsplätze. fixed a typo in isAusbildungsleitung, 
**Reference:**
Issue: #176 
---
=> 🔀✨ Sortierte meldezeitraeume in der Meldung

praktikumsplaner-backend/pom.xml, praktikumsplaner-backend/src/main/java/de/muenchen/oss/praktikumsplaner/configuration/NoSecurityConfiguration.java, praktikumsplaner-backend/src/main/java/de/muenchen/oss/praktikumsplaner/configuration/SecurityConfiguration.java, praktikumsplaner-backend/src/main/java/de/muenchen/oss/praktikumsplaner/repository/NwkRepository.java, praktikumsplaner-backend/src/main/java/de/muenchen/oss/praktikumsplaner/rest/MeldezeitraumController.java, praktikumsplaner-backend/src/main/java/de/muenchen/oss/praktikumsplaner/rest/PraktikumsstellenController.java
LCM of the spring boot version
- 3.0.7 -> 3.1.5 -> 3.2.1
- update of plugin versions
- fix of one cve (commons-test)
**Reference:**
Issue: #204 
@mirrodi @AnHo314
---
=> LCM spring boot version

doc/src/features/meldezeitraum.md
greetings
I think it looks better with correct whitespace
**Reference:**
Issue: #XXX
---
=> 🔀📝 add missing whitespace to meldezeitraum.md

praktikumsplaner-frontend/frontend/src/views/praktikumsplaetze/MeldungAusbildung.vue, praktikumsplaner-frontend/frontend/src/views/praktikumsplaetze/MeldungStudium.vue
Added the missing circular loaders when creating a Praktikumsstelle
**Reference:**
Issue: #182 
---
=> 🔀🐛 missing circular loader Meldung

praktikumsplaner-frontend/frontend/src/api/MeldezeitraumService.ts, praktikumsplaner-frontend/frontend/src/api/NwkService.ts, praktikumsplaner-frontend/frontend/src/api/PraktikumsstellenService.ts, praktikumsplaner-frontend/frontend/src/components/nachwuchskraefte/NwkCreateDialog.vue
HOTFIX
Changed saveNwk to work with new errors
=> 🚑️ Fixed saveNwk

praktikumsplaner-frontend/frontend/src/components/nachwuchskraefte/NwkCreateDialog.vue
Form validation didn't work for NwkCreateDialog. Now it does.
**Reference:**
Issue: #234
---
=> 🔀 🚑️ Hotfix nwkCreateDialog

praktikumsplaner-frontend/frontend/index.html
Der Text der angezeigt wird, wenn JavaScript im Browser deaktiviert ist, wurde auf unsere Applikation angepasst.
**Reference:**
Issue: #228 
---
=> 🔀🐛 JavaScript deaktiviert Error Message angepasst

praktikumsplaner-frontend/frontend/src/components/assign/NwkCard.vue
The NwkCard had bugs in AssignView. The name was truncated too early.
**Reference:**
Issue: #229
---
=> 🔀🐛 NwkName Zuweisungsliste

praktikumsplaner-frontend/frontend/src/components/assign/QueryPraktikumsPeriodDialog.vue, praktikumsplaner-frontend/frontend/src/components/meldezeitraeume/CreateMeldezeitraum.vue, praktikumsplaner-frontend/frontend/src/components/nachwuchskraefte/ExcelImportNwk.vue, praktikumsplaner-frontend/frontend/src/components/nachwuchskraefte/NwkCreateDialog.vue, praktikumsplaner-frontend/frontend/src/components/nachwuchskraefte/NwkUpdateDialog.vue, praktikumsplaner-frontend/frontend/src/views/praktikumsplaetze/MeldungAusbildung.vue, praktikumsplaner-frontend/frontend/src/views/praktikumsplaetze/MeldungStudium.vue
Form validation was restructured, because of Vue/Vuetify 3 changes.
**Reference:**
Issue: #240
---
=> 🔀🐛 Form Validation

praktikumsplaner-frontend/apigateway/src/main/java/de/muenchen/oss/praktikumsplaner/configuration/CustomWebExceptionHandler.java, praktikumsplaner-frontend/apigateway/src/main/resources/application.yml
A wrong spring session time out led to an unusable application when the sso timeout was exceeded.
This PR sets the timeout to the correct value. (This could also be set in the env. variables of the deployed application to adapt to different environments)
It also includes an ExceptionHandler that handles the exception that is thrown when the session is invalid and enforces a relogin on the sso to get a new session. 
**Reference:**
Issue: #194 
=> 🔀🐛🛂 session timeout app unusable

praktikumsplaner-backend/src/main/resources/db/migration/V15__Praktikumsstellen_cascade_on_delete.sql
removed public from table names to fix database
=> 🔀🚑️ removed public from table names

praktikumsplaner-frontend/frontend/src/components/nachwuchskraefte/NwkCreateDialog.vue
Added a cancel() to perform close and clear action. 
**Reference:**
Issue: #248
=> 🔀🐛 Fixed missing clear of form after exiting 

.github/workflows/release-specific-docker-tag.yml
Add github action to deploy a specific tag to docker
=> 🔀👷 GitHub action for specific release

praktikumsplaner-frontend/apigateway/pom.xml, praktikumsplaner-frontend/apigateway/src/main/java/de/muenchen/oss/praktikumsplaner/filter/GlobalAuthenticationErrorFilter.java, praktikumsplaner-frontend/apigateway/src/main/java/de/muenchen/oss/praktikumsplaner/filter/GlobalBackend5xxTo400Mapper.java
Upgraded spring cloud to 2023.0.0
Deleted hazelcast-all dependency
**Reference:**
Issue: #205
=> 🔀 ⬆️ Upgrade frontend to spring boot 3.2.3

praktikumsplaner-frontend/frontend/src/views/AssignView.vue
The right column of the assignview was wrapped.
**Reference:**
Issue: #257
=> 🔀 🐛Fixed wrapped AssignView

praktikumsplaner-frontend/frontend/src/api/ExportService.ts, praktikumsplaner-frontend/frontend/src/api/MailService.ts, praktikumsplaner-frontend/frontend/src/api/MeldezeitraumService.ts, praktikumsplaner-frontend/frontend/src/api/NwkService.ts, praktikumsplaner-frontend/frontend/src/api/PraktikumsstellenService.ts, praktikumsplaner-frontend/frontend/src/components/assign/ExcelExport.vue, praktikumsplaner-frontend/frontend/src/components/assign/PraktikumsstelleCardZuweisung.vue, praktikumsplaner-frontend/frontend/src/components/assign/QueryPraktikumsPeriodDialog.vue, praktikumsplaner-frontend/frontend/src/components/meldezeitraeume/MeldezeitraumList.vue, praktikumsplaner-frontend/frontend/src/components/nachwuchskraefte/ActiveNwkList.vue, praktikumsplaner-frontend/frontend/src/components/nachwuchskraefte/ExcelImportNwk.vue, praktikumsplaner-frontend/frontend/src/components/nachwuchskraefte/NwkCreateDialog.vue, praktikumsplaner-frontend/frontend/src/components/nachwuchskraefte/NwkUpdateDialog.vue, praktikumsplaner-frontend/frontend/src/views/AssignView.vue, praktikumsplaner-frontend/frontend/src/views/MeldezeitraeumeView.vue, praktikumsplaner-frontend/frontend/src/views/praktikumsplaetze/MeldungAusbildung.vue, praktikumsplaner-frontend/frontend/src/views/praktikumsplaetze/MeldungStudium.vue, praktikumsplaner-frontend/frontend/src/views/praktikumsplaetze/PraktikumsplaetzeView.vue
Relocated loading logic. From component to service.
**Reference:**
Issue: #212
=> 🔀♻️ loading logic relocation

praktikumsplaner-frontend/frontend/src/components/praktikumsplaetze/Meldung/AusbilderEmailInput.vue, praktikumsplaner-frontend/frontend/src/components/praktikumsplaetze/Meldung/AusbilderInput.vue, praktikumsplaner-frontend/frontend/src/components/praktikumsplaetze/Meldung/AusbildungsJahrSelect.vue, praktikumsplaner-frontend/frontend/src/components/praktikumsplaetze/Meldung/AusbildungsrichtungSelect.vue, praktikumsplaner-frontend/frontend/src/components/praktikumsplaetze/Meldung/DienststellenInput.vue, praktikumsplaner-frontend/frontend/src/components/praktikumsplaetze/Meldung/DringlichkeitSelect.vue, praktikumsplaner-frontend/frontend/src/components/praktikumsplaetze/Meldung/MeldezeitraumSelect.vue, praktikumsplaner-frontend/frontend/src/components/praktikumsplaetze/Meldung/NamentlicheAnforderungInput.vue, praktikumsplaner-frontend/frontend/src/components/praktikumsplaetze/Meldung/ProgrammierKenntnisseSelect.vue, praktikumsplaner-frontend/frontend/src/components/praktikumsplaetze/Meldung/ReferatSelect.vue, praktikumsplaner-frontend/frontend/src/components/praktikumsplaetze/Meldung/StudienrichtungSelect.vue, praktikumsplaner-frontend/frontend/src/components/praktikumsplaetze/Meldung/StudiensemesterSelect.vue, praktikumsplaner-frontend/frontend/src/components/praktikumsplaetze/Meldung/TaetigkeitenInput.vue
All not required fields are now clearable
**Reference:**
Issue: #190 
---
=> 🔀✨ Clearable not required fields

doc/src/features/Zuweisung.md, praktikumsplaner-frontend/frontend/src/components/assign/NwkCard.vue, praktikumsplaner-frontend/frontend/src/views/AssignView.vue, praktikumsplaner-frontend/frontend/src/views/praktikumsplaetze/PraktikumsplaetzeView.vue
With this pull request the possibility to scroll in both lists in the assign view was added
**Reference:**
Issue: #260 
---
=> 🔀✨ Scrollable Lists in AssignView

praktikumsplaner-frontend/frontend/src/components/assign/NwkCard.vue, praktikumsplaner-frontend/frontend/src/components/nachwuchskraefte/VorlesungstageSelect.vue, praktikumsplaner-frontend/frontend/src/components/praktikumsplaetze/Meldung/AusbildungsJahrSelect.vue, praktikumsplaner-frontend/frontend/src/components/praktikumsplaetze/Meldung/StudiensemesterSelect.vue
Fixed the gray checkbox bug when not focused.
**Reference:**
Issue: #265
=> 🔀💄 Fixed gray checkbox bug in selects

.github/workflows/release-doc.yml
Fix für https://github.com/it-at-m/Praktikumsplaner/actions/runs/9059962928/job/24888670645
**Reference:**
---
- no explicit DoD required
=> fix cache path

.github/workflows/release-doc.yml
- fix working dir
- fix publish dir
**Reference:**
---
- success verified via manual run of workflow https://github.com/it-at-m/Praktikumsplaner/actions/runs/9060414230/job/24890050649
=> Fix release doc workflow

praktikumsplaner-frontend/frontend/src/components/praktikumsplaetze/Meldung/AusbildungsrichtungSelect.vue
fix build error cause of missing nullable property
**Reference:**
Issue: #333
---
- [~] Unittests gepflegt
- [~] Dokumentation ist gepflegt
=> make disabled nullable

praktikumsplaner-backend/pom.xml
allows the use up to postgres 17
=> Add flyway postgres dependency

praktikumsplaner-frontend/frontend/package-lock.json, praktikumsplaner-frontend/frontend/package.json, praktikumsplaner-frontend/frontend/src/main.ts, praktikumsplaner-frontend/frontend/tsconfig.json, praktikumsplaner-frontend/frontend/vite.config.ts
**Description:** 
adept it-at-m/refarch-templates#622
=> config to resolve font locally
